version: '3'
services:
  reporting:
    build:
      args:
        MONGO_CONNECTION_URI: ${MONGO_CONNECTION_URI}
        SMTP_USER: ${SMTP_USER}
        SMTP_PASSWORD: ${SMTP_PASSWORD}
      dockerfile: Dockerfile
    image: ricardolandinez/reporting_estupendo
    container_name: reporting_estupendo
    volumes:
      - ./logs:/app/logs
